language: python
python:
  - 3.5

install:
  - pip install Django

script:
  - ./runtests.sh

notifications:
  slack:
    rooms:
      - oratorio-cse403:JjtLhql5ybLqIzcwRzrSPtu6
    on-success: never
    on-failure: always
  email:
    recipients:
      - cse403-oratorio@googlegroups.com
    on-success: never
    on-failure: always
