language: python
python:
  - 2.7

install:
  - pip install django==1.10 watson-developer-cloud oauth2client coverage django-nose
env:
  - SECRET_KEY=oratorio

script:
  - cd oratorio
  - npm install
  - python manage.py makemigrations coach
  - python manage.py migrate coach
  - grunt test --verbose --force
  - coverage run --source=coach.models,coach.analyzer,coach.views ./manage.py test
  - coverage report

notifications:
  slack:
    rooms:
      - oratorio-cse403:JjtLhql5ybLqIzcwRzrSPtu6
    on-success: change
    on-failure: always
  email:
    recipients:
      - cse403-oratorio@googlegroups.com
    on-success: never
    on-failure: always
